name: Cherry Pick Commits

on:
  workflow_dispatch:
    inputs:
      releases:
        description: 'Release numbers (space-separated, e.g. 3.2.0 3.3.0)'
        required: true
      commits:
        description: 'Commit hashes (space-separated)'
        required: true

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Cherry-pick and create PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASES="${{ github.event.inputs.releases }}"
          COMMITS="${{ github.event.inputs.commits }}"
          DEFAULT_REVIEWERS="nukulb"
          USERNAME="${GITHUB_ACTOR}"
          for RELEASE in $RELEASES; do
            BASE_BRANCH="releases/$RELEASE"
            BRANCH_NAME="${USERNAME}/cherry-pick-${RELEASE}-$(date +%Y%m%d%H%M%S)"
            git fetch origin
            git checkout "$BASE_BRANCH"
            git pull origin "$BASE_BRANCH"
            git checkout -b "$BRANCH_NAME"
            for COMMIT in $COMMITS; do
              git cherry-pick "$COMMIT"
            done
            git push origin "$BRANCH_NAME"
            PR_TITLE="Cherry-pick to $RELEASE"
            PR_BODY="Cherry-pick of commits: $COMMITS"
            gh pr create --base "$BASE_BRANCH" --head "$BRANCH_NAME" --title "$PR_TITLE" --body "$PR_BODY" --reviewer "$DEFAULT_REVIEWERS"
          done
